In [1]:
from trajectory_tools.loaders import LammpsDumpDirectoryLoader
from trajectory_tools.writers import XYZStructureWriter
import numpy as np
from pymatgen.core import Species

# Load the trajectory
loader = LammpsDumpDirectoryLoader("../dat_directory", None)
print(loader.get_total_steps())

structures = [s for s in loader]


Loading slice None from 4 files
4


In [2]:
#create the writer
from trajectory_tools.writers.structure_writer import StructureWriter
from trajectory_tools.transforms import AverageTrajectoryCreator

writer : StructureWriter = XYZStructureWriter(path="test.xyz")

average_creator = AverageTrajectoryCreator(structures, 
                                           species_to_average={'Li':None},
                                           trajectory_writer=writer,
                                           average_window=2,
                                           )


In [ ]:
print(structures[0].cart_coords)

[[2.98266394e+00 5.32340187e+01 3.23840147e-02]
 [7.61510489e-02 2.94611936e+00 5.32292270e+01]
 [1.55787782e+00 1.51728693e+00 1.45544225e+00]
 ...
 [4.27973569e+01 4.28778572e+01 4.87472449e+01]
 [4.28381927e+01 4.87840877e+01 4.87480436e+01]
 [4.87438908e+01 4.88012313e+01 4.89155396e+01]]


In [4]:
averaged_structures = average_creator.process_trajectory()

Processing [------------------------------] 0/4 (0.00%)

AttributeError: 'NoneType' object has no attribute 'items'